#!/usr/bin/env bash
error() { echo -e "\033[0;31merror:\033[0m $1"; exit 7; }

## Commit Message ##
# Keywords
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor)(\(.+?\))?\!?: .{1,}$"
then
  error "Commit Message is invalid"
fi

# Length
if ! head -1 "$1" | grep -qE "^.{1,50}$"
then
  error "Commit Message is too long"
fi
