[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = [
  "--write",
  "--list-different",
  "--ignore-unknown",
]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.ts",
  "*.yaml",
]
