name = "site"
main = "index.js"
compatibility_date = "2025-12-15"

[assets]
binding = "ASSETS"
directory = "./public"
not_found_handling = "404-page"
run_worker_first = true

[env.production]
routes = [
  { pattern = "maydayv7.dev", custom_domain = true },
  { pattern = "www.maydayv7.dev", custom_domain = true }
]
