# Site URL
base_url = "/"
title = "maydayv7"
description = "My Personal Website"

# Default Language used in Feeds
default_language = "en"

# Compile all '.scss' files in './sass'
compile_sass = true

# Build search index to be used later by JS Library
build_search_index = true

# RSS Feed
generate_feeds = true
feed_filenames = ["rss.xml"]

# Taxonomies
# See <https://www.getzola.org/documentation/content/taxonomies/>
taxonomies = [
  { name = "series", feed = true, paginate_by = 10 },
  { name = "tags", feed = true, paginate_by = 10 },
]

[markdown]
# Parser Settings
render_emoji = true
smart_punctuation = false
lazy_async_image = true
github_alerts = true
insert_anchor_links = "right"

# External Link Settings
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[markdown.highlighting]
# Syntax Highlighting
style = "class"
theme = "github-dark"

[search]
# Site Search Settings
include_title = true
include_description = false
include_path = false
include_content = true
index_format = "fuse_javascript"

[extra]
# Site Theme
theme_color = "red"
color_schemes = ["black", "blue", "red"]

# Enable Math Typesetting with KaTeX
# Use 'math=true' in [extra] on individual pages
math_katex = true

# Generate Table of Contents for all articles
# Use 'ToC = true' in [extra] on individual pages
table_of_contents = false

# Logo
favicon = "website.ico"
logo_text = "maydayv7"
center = true

# Allow Editing Articles
# Use 'edit = true' in [extra] on individual pages
edit_page = true
repo_url = "https://github.com/maydayv7/dotfiles/blob/stable/site"

# License
author = "maydayv7"
copyright = "V7"
google_analytics_tracking_id = "G-26PNXDYZNZ"

# Page Comments
# Use 'comments = true' in [extra] on individual pages
disqus = { enabled = false, short_name = "maydayv7" }
giscus = { enabled = true, repo = "maydayv7/dotfiles", repo_id = "R_kgDOHEEEUA", category = "Site", category_id = "DIC_kwDOHEEEUM4C0c1O" }

# Main Menu
main_menu_items = [
  { url = "/blog/", name = "Blog" },
  { url = "/projects/", name = "Projects" },
  { url = "/about/", name = "About" },
  { url = "https://git.maydayv7.cc", name = "Git", external = true },
]

# Socials Bar
email = "mailto:mail@maydayv7.cc"
feed_path = "/rss.xml"
reddit_profile = "https://reddit.com/u/maydayv7"
github_profile = "https://github.com/maydayv7"
discord_profile = "https://discord.com/users/519513852648357929"

# Webring
webring = true
webring_name = "❄️"
webring_url = "https://nixwebr.ing"
