exec-once = @greeter; hyprctl dispatch exit

windowrule = fullscreen on, stay_focused on, match:class ^(.*)$
monitor = , preferred, auto, 1

animations:enabled = false
misc {
  background_color = rgb(@base00)
  disable_autoreload = true
  disable_hyprland_logo = true
  disable_splash_rendering = true
  disable_hyprland_guiutils_check = true
  enable_anr_dialog = false
  force_default_wallpaper = 0
}

ecosystem {
  no_update_news = true
  no_donation_nag = true
}
