[pyprland]
plugins = [
  "magnify",
  "scratchpads",
  "toggle_special"
]

[scratchpads.top]
animation = "fromTop"
lazy = true
size = "75% 60%"

[scratchpads.bottom]
animation = "fromBottom"
size = "75% 60%"
margin = 30
lazy = true

[scratchpads.calc]
command = "qalculate-gtk"
class = "qalculate-gtk"
use = "top"
unfocus = "hide"

[scratchpads.term]
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
use = "top"
unfocus = "hide"

[scratchpads.clip]
use = "bottom"
command = "kitty --class kitty-clip 'clipse'"
class = "kitty-clip"

[scratchpads.emoji]
use = "bottom"
command = "smile"
class = "it.mijorus.smile"
unfocus = "hide"
