[pyprland]
plugins = [
  "scratchpads",
  "toggle_special"
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.clip]
animation = "fromBottom"
command = "kitty --class clipse clipse $PPID"
class = "clipse"
lazy = true
size = "75% 65%"
margin = 30

[scratchpads.bluetooth]
animation = "fromRight"
command = "overskride"
class = "io.github.kaii_lb.Overskride"
lazy = true
size = "50% 90%"
margin = 30
unfocus = "hide"
excludes = ["displays", "network", "volume"]

[scratchpads.displays]
animation = "fromRight"
command = "nwg-displays"
class = "nwg-displays"
lazy = true
size = "50% 90%"
margin = 30
unfocus = "hide"
excludes = ["bluetooth", "network", "volume"]

[scratchpads.network]
animation = "fromRight"
command = "kitty --class kitty-nm nmtui"
class = "kitty-nm"
lazy = true
size = "50% 90%"
margin = 30
unfocus = "hide"
excludes = ["bluetooth", "displays", "volume"]

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "50% 90%"
margin = 30
unfocus = "hide"
excludes = ["bluetooth", "displays", "network"]
