[overview]
command = [ "hyprctl", "dispatch", "hyprexpo:expo", "on" ]
locations = [ "top_left" ]
size = 10
timeout_ms = 200

[workspace]
command = [ "hyprctl", "dispatch", "split:workspace", "empty" ]
locations = [ "top_right" ]
size = 10
timeout_ms = 200
