## My ZSH Config ##
# Plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# Powerlevel10K Prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Find The Command
source /usr/share/doc/find-the-command/ftc.zsh noprompt quiet

bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[3;5~' kill-word
bindkey '^[[3~'   delete-char
bindkey "^[[5~"   beginning-of-history
bindkey "^[[6~"   end-of-history
bindkey '^[[A'    up-line-or-search
bindkey '^[[B'    down-line-or-search
bindkey '^[[C'    forward-char
bindkey '^[[D'    backward-char
bindkey '^[[F'    end-of-line
bindkey '^[[H'    beginning-of-line
bindkey '^J'      backward-kill-line

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=1000
setopt SHARE_HISTORY

alias hi="echo 'Hi there. How are you?'"
alias bye="exit"
alias c="bat"
alias l="eza -b -h -l -F --octal-permissions --icons --time-style iso"
alias grep="grep --color"
alias edit="sudo $EDITOR"
alias sike="neowofetch --ascii_distro arch"
