# YASB Panel Configuration
watch_stylesheet: true
watch_config: true
debug: false

bars:
  panel:
    enabled: true
    screens: ["*"]
    class_name: "yasb-panel"
    alignment:
      position: "top"
      align: "center"
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 26
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: true
      dark_mode: true
      round_corners: false
      border_color: None
    widgets:
      left: [
          "task_view",
          # "home",
          "windows_workspaces",
          "active_window",
          "media",
          # "apps",
          # "taskbar",
        ]
      center: []
      right: [
          # "cpu",
          # "gpu",
          # "memory",
          # "disk",
          # "traffic",
          "microphone",
          "volume",
          "brightness",
          "battery",
          "bluetooth",
          "wifi",
          "weather",
          "clock",
          "power_menu",
        ]

widgets:
  task_view:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\ue154</span>"
      label_alt: "<span>\ue154</span>"
      class_name: "task-view-widget"
      callbacks:
        on_left: "exec explorer.exe shell:::{3080F90E-D7AD-11D9-BD98-0000947B0257}"
        on_middle: "do_nothing"
        on_right: "exec winver"

  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue62a</span>"
      system_menu: true
      power_menu: false
      blur: true
      border_color: "system"
      round_corners_type: "normal"
      menu_labels:
        about: "\ue66A  About This PC"
        system: "\uF423  System Settings"
        task_manager: "\uf437  Task Manager"
        hibernate: "\uf28e  Hibernate"
        sleep: "\u23fe  Sleep"
        restart: "\uead2  Restart"
        shutdown: "\uf011  Shutdown"
        lock: "\uea75  Lock"
        logout: "\udb80\udf43  Logout"
      menu_list:
        - { title: "\uE617  Home", path: "~" }
        - { title: "\udb80\udd20  Downloads", path: "~\\Downloads" }
        - { title: "\udb80\ude1a  Documents", path: "~\\Documents" }
        - { title: "\uf03e  Pictures", path: "~\\Pictures" }

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[app_name]}"
      label_alt: "{win[title]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 50
      max_length_ellipsis: "..."
      monitor_exclusive: false
      ignore_window:
        processes:
          - "Rainmeter.exe"
        classes:
          - "RainmeterMeterWindow"
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  windows_workspaces:
    type: "yasb.windows_desktops.WorkspaceWidget"
    options:
      label_workspace_btn: "\u25cb"
      label_workspace_active_btn: "\udb81\udc3e"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span>  {%a %d %b   %H:%M}"
      label_alt: "{%A %d %B %Y %H:%M:%S}"
      timezones: []
      calendar:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        show_holidays: true
        show_week_numbers: true
        holiday_color: "#FF6464"

  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - { icon: "\uf0a2", launch: "notification_center" }
        - { icon: "\ueb51", launch: "quick_settings" }
        - { icon: "\uf46a", launch: "cmd /c start ms-settings:windowsupdate" }
        - { icon: "\uf422", launch: "search" }
        - { icon: "\ueb03", launch: "cmd /c Taskmgr", name: "Task Manager" }
        - { icon: "\uf489", launch: "wt", name: "Windows Terminal" }
        - { icon: "\udb82\ude1e", launch: "cmd /c code", name: "VS Code" }
        - {
            icon: "\uf1b6",
            launch: "C:/Program Files (x86)/Steam/Steam.exe",
            name: "Steam",
          }

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      animation:
        enabled: true
      preview:
        enabled: true
        width: 250
        delay: 400
        padding: 12
      callbacks:
        on_middle: "close_app"

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\u266a</span> {title}"
      label_alt: "<span>\u266a</span> {artist}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "toggle_play_pause"
        on_right: "toggle_label"
      max_field_size:
        label: 45
        label_alt: 80
      show_thumbnail: false
      controls_only: false
      controls_left: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 10
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: {min_temp}/{max_temp}"
      api_key: "$env:YASB_WEATHER_API_KEY"
      location: "auto:ip"
      show_alerts: true
      hide_decimal: true
      units: "metric"
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyDay: "\udb81\udd98"
        snowyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        default: "\uebaa"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        icon_size: 64

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\ueea1</span> {info[percent][total]}%"
      label_alt: "<span>\ueea1</span> {info[histograms][cpu_percent]}"
      update_interval: 1000
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "do_nothing"
        on_middle: "exec cmd /c Taskmgr"
        on_right: "toggle_label"

  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[temp]}°C"
      label_alt: "<span>\uf4bc</span> {info[temp]}°C | {info[mem_used]} / {info[mem_total]}"
      update_interval: 2000
      gpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "do_nothing"
        on_middle: "exec cmd /c Taskmgr"
        on_right: "toggle_label"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_used} / {virtual_mem_total}"
      label_alt: "<span>\uf4bc</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "do_nothing"
        on_middle: "exec cmd /c Taskmgr"
        on_right: "toggle_label"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+

  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span>\uf473</span> Disks"
      label_alt: "<span>\uf473</span> {volume_label} {space[used][gb]} / {space[total][gb]}"
      volume_label: "C"
      decimal_display: 1
      update_interval: 60
      group_label:
        volume_labels:
          [
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z",
          ]
        show_label_name: true
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_group"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      disk_thresholds:
        low: 25
        medium: 50
        high: 90

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span class='download'>\uea9a {download_speed}</span><span class='upload'>{upload_speed} \ueaa1</span>"
      label_alt: "<span class='download'>\uea9a {download_speed}</span><span class='upload'>{upload_speed} \ueaa1</span>"
      update_interval: 1000
      hide_if_offline: true
      speed_unit: "bytes"
      max_label_length_align: "center"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network-status"
        on_right: "do_nothing"

  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span>"
      mute_text: "Mute"
      icons:
        normal: "\ue720"
        muted: "\uf12e"
      mic_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_mic_menu"
        on_middle: "exec cmd.exe /c start ms-settings:sound"
        on_right: "toggle_mute"

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      mute_text: "Mute"
      volume_icons:
        - "\ue74f" # Mute
        - "\ue992" # 10%
        - "\ue993" # 30%
        - "\ue994" # 60%
        - "\ue995" # 100%
      callbacks:
        on_left: "toggle_volume_menu"
        on_middle: "exec cmd.exe /c start ms-settings:sound"
        on_right: "toggle_mute"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"

  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}%"
      brightness_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_brightness_menu"
        on_middle: "exec cmd /c start ms-settings:display"
        on_right: "do_nothing"
      brightness_icons: ["\ue706", "\ue706", "\ue706", "\ue706"]

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "<span>{wifi_icon}</span> {wifi_name} {wifi_strength}%"
      update_interval: 5000
      get_exact_wifi_strength: true
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span> {ip_addr}"
      ethernet_icon: "\ue839"
      wifi_icons: ["\uec3c", "\uec3d", "\uec3e", "\uec3e", "\uec3f"]
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0

  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{device_name}"
      label_no_device: "Not Connected"
      label_device_separator: ", "
      max_length: 15
      max_length_ellipsis: "..."
      icons:
        bluetooth_on: "\uec41"
        bluetooth_off: "\ueb90"
        bluetooth_connected: "\ue702"
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:bluetooth"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% ({time_remaining})"
      update_interval: 5000
      hide_unsupported: true
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: true
        blink_interval: 800
      status_thresholds:
        critical: 10
        low: 25
        medium: 60
        high: 90
        full: 100
      status_icons:
        icon_charging: "\ue945"
        icon_critical: "\ue851"
        icon_low: "\ue853"
        icon_medium: "\ue855"
        icon_high: "\ue857"
        icon_full: "\ue859"
      callbacks:
        on_left: "exec cmd /c start ms-settings:powersleep"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\ue7e8"
      uptime: true
      blur: false
      blur_background: true
      animation_duration: 300
      button_row: 3
      buttons:
        lock: ["\uea75", "Lock"]
        signout: ["\udb80\udf43", "Sign out"]
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        hibernate: ["\uf28e", "Hibernate"]
        cancel: ["\udb81\udf3a", "Cancel"]
