{
  appimage = ["application/x-executable"];

  archive = [
    "application/x-7z-compressed"
    "application/x-7z-compressed-tar"
    "application/x-bzip"
    "application/x-bzip-compressed-tar"
    "application/x-compress"
    "application/x-compressed-tar"
    "application/x-cpio"
    "application/x-gzip"
    "application/x-lha"
    "application/x-lzip"
    "application/x-lzip-compressed-tar"
    "application/x-lzma"
    "application/x-lzma-compressed-tar"
    "application/x-tar"
    "application/x-tarz"
    "application/x-xar"
    "application/x-xz"
    "application/x-xz-compressed-tar"
    "application/zip"
    "application/gzip"
    "application/bzip2"
    "application/vnd.rar"
  ];

  audio = [
    "audio/aac"
    "audio/flac"
    "audio/mp3"
    "audio/mpeg"
    "audio/ogg"
    "audio/opus"
    "audio/wav"
    "audio/webm"
    "audio/x-aac"
    "audio/x-aiff"
    "audio/x-ape"
    "audio/x-flac"
    "audio/x-m4a"
    "audio/x-m4b"
    "audio/x-matroska"
    "audio/x-mp1"
    "audio/x-mp2"
    "audio/x-mp3"
    "audio/x-mpeg"
    "audio/x-mpegurl"
    "audio/x-mpg"
    "audio/x-opus+ogg"
    "audio/x-pn-aiff"
    "audio/x-pn-au"
    "audio/x-pn-wav"
    "audio/x-speex"
    "audio/x-vorbis"
    "audio/x-vorbis+ogg"
    "audio/x-wavpack"
  ];

  browser = [
    "application/x-extension-htm"
    "application/x-extension-html"
    "application/x-extension-shtml"
    "application/x-extension-xht"
    "application/x-extension-xhtml"
    "application/xhtml+xml"
    "text/html"
    "x-scheme-handler/about"
    "x-scheme-handler/ftp"
    "x-scheme-handler/http"
    "x-scheme-handler/https"
    "x-scheme-handler/unknown"
  ];

  calendar = [
    "text/calendar"
    "x-scheme-handler/webcal"
  ];

  code = [
    "application/json"
    "application/toml"
    "application/x-shellscript"
    "application/x-yaml"
    "text/x-c"
    "text/x-c++"
    "text/x-c++src"
    "text/x-chdr"
    "text/x-cmake"
    "text/x-java"
    "text/x-lua"
    "text/x-makefile"
    "text/x-markdown"
    "text/x-nix"
    "text/x-python"
    "text/x-rust"
    "text/x-scala"
    "text/x-shellscript"
    "text/x-toml"
    "text/x-yaml"
  ];

  directory = ["inode/directory"];

  document = [
    "application/illustrator"
    "application/oxps"
    "application/postscript"
    "application/vnd.comicbook-rar"
    "application/vnd.comicbook+zip"
    "application/vnd.ms-xpsdocument"
    "application/x-bzpdf"
    "application/x-bzpostscript"
    "application/x-cb7"
    "application/x-cbr"
    "application/x-cbt"
    "application/x-cbz"
    "application/x-ext-cb7"
    "application/x-ext-cbr"
    "application/x-ext-cbt"
    "application/x-ext-cbz"
    "application/x-ext-djv"
    "application/x-ext-djvu"
    "application/x-ext-eps"
    "application/x-ext-pdf"
    "application/x-ext-ps"
    "application/x-gzpdf"
    "application/x-gzpostscript"
    "application/x-xzpdf"
    "image/vnd.djvu"
    "image/x-bzeps"
    "image/x-eps"
    "image/x-gzeps"
  ];

  font = [
    "application/vnd.ms-opentype"
    "application/x-font-ttf"
    "font/otf"
    "font/ttf"
    "font/woff"
    "font/woff2"
  ];

  image = [
    "image/avif"
    "image/bmp"
    "image/gif"
    "image/heic"
    "image/heif"
    "image/jpeg"
    "image/jpg"
    "image/jxl"
    "image/png"
    "image/svg+xml-compressed"
    "image/svg+xml"
    "image/tiff"
    "image/vnd-ms.dds"
    "image/vnd.microsoft.icon"
    "image/vnd.microsoft.icon"
    "image/vnd.radiance"
    "image/webp"
    "image/x-dds"
    "image/x-exr"
    "image/x-icon"
    "image/x-portable-anymap"
    "image/x-portable-bitmap"
    "image/x-portable-graymap"
    "image/x-portable-pixmap"
    "image/x-qoi;image/svg+xml"
    "image/x-tga"
  ];

  latex = ["text/x-tex"];

  magnet = ["x-scheme-handler/magnet"];

  mail = ["x-scheme-handler/mailto"];

  markdown = ["text/markdown"];

  office = [
    "application/rtf"
    "application/vnd.oasis.opendocument.text"
    "application/vnd.oasis.opendocument.spreadsheet"
    "application/vnd.oasis.opendocument.presentation"
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    "application/msword"
    "application/vnd.ms-excel"
    "application/vnd.ms-powerpoint"
  ];

  password = [
    "application/x-keepass2"
    "application/x-keepass"
  ];

  pdf = ["application/pdf"];

  text = [
    "text/plain"
    "text/css"
    "text/ecmascript"
    "text/javascript"
    "text/x-script.python"
    "text/x-script.sh"
    "text/x-script.zsh"
    "text/xml"
  ];

  video = [
    "application/mxf"
    "application/ogg"
    "application/ram"
    "application/sdp"
    "application/smil"
    "application/smil+xml"
    "application/vnd.apple.mpegurl"
    "application/vnd.ms-asf"
    "application/vnd.ms-wpl"
    "application/vnd.rn-realmedia-vbr"
    "application/vnd.rn-realmedia"
    "application/x-extension-mp4"
    "application/x-flash-video"
    "application/x-matroska"
    "application/x-netshow-channel"
    "application/x-ogg"
    "application/x-quicktime-media-link"
    "application/x-quicktimeplayer"
    "application/x-shorten"
    "application/x-smil"
    "application/xspf+xml"
    "video/3gp"
    "video/3gpp"
    "video/3gpp2"
    "video/divx"
    "video/dv"
    "video/fli"
    "video/mp2t"
    "video/mp4"
    "video/mp4v-es"
    "video/mpeg-system"
    "video/mpeg"
    "video/msvideo"
    "video/ogg"
    "video/quicktime"
    "video/vivo"
    "video/vnd.divx"
    "video/vnd.rn-realvideo"
    "video/vnd.vivo"
    "video/webm"
    "video/x-anim"
    "video/x-avi"
    "video/x-flc"
    "video/x-fli"
    "video/x-flic"
    "video/x-flv"
    "video/x-m4v"
    "video/x-matroska"
    "video/x-mpeg"
    "video/x-mpeg2"
    "video/x-ms-asf-plugin"
    "video/x-ms-asf"
    "video/x-ms-asx"
    "video/x-ms-wm"
    "video/x-ms-wmv"
    "video/x-ms-wmx"
    "video/x-ms-wvx"
    "video/x-msvideo"
    "video/x-nsv"
    "video/x-ogm+ogg"
    "video/x-theora"
    "video/x-theora+ogg"
    "video/x-totem-stream"
    "x-content/video-dvd"
    "x-content/video-svcd"
    "x-content/video-vcd"
    "x-scheme-handler/icy"
    "x-scheme-handler/icyx"
    "x-scheme-handler/mmsh"
    "x-scheme-handler/net"
    "x-scheme-handler/pnm"
    "x-scheme-handler/rtmp"
    "x-scheme-handler/uvox"
  ];

  virtualization = [
    "application/x-cd-image"
    "application/x-qemu-disk"
    "application/x-virtualbox-hdd"
    "application/x-virtualbox-vbox"
  ];
}
