backend = "auto"
transition_mode = "start_at"

smoothing = true
startup_duration = 0.5
shutdown_duration = 0.5
adaptive_interval = 1

sunset = "19:00:00"
sunrise = "06:00:00"
transition_duration = 15
night_temp = 4000
day_temp = 6500
night_gamma = 90
day_gamma = 100
update_interval = 60
