#!/usr/bin/env bash
error() { echo -e "\033[0;31merror:\033[0m $1"; exit 7; }

## Pre-Commit Checks ##
# Syntax
nixos format ./.

if [ "$(git branch --show-current)" == "stable" ]
then
  nixos check ./. || error "Invalid Syntax"
fi
