# Build Device Configuration
device:
  stage: build
  only:
    - tags
  except:
    - /^(?!stable).+@/
  allow_failure: true
  variables:
    CACHIX_AUTH_TOKEN: $CACHIX_TOKEN
    CACHIX_CACHE_NAME: maydayv7-dotfiles
  parallel:
    matrix:
      - DEVICE: [Vortex, Futura]
  before_script:
    - nix profile install nixpkgs#cachix
    - cachix use $CACHIX_CACHE_NAME
  script: cachix watch-exec $CACHIX_CACHE_NAME nix build .#nixosConfigurations.$DEVICE.config.system.build.toplevel -- -L --show-trace

# Build Install Media Image
iso:
  stage: build
  only:
    - tags
  except:
    - /^(?!stable).+@/
  variables:
    ISO: gnome # Default Variant
  before_script:
    - echo "Job ID - $CI_JOB_ID"
    - echo JOB_ID=$CI_JOB_ID >> build_iso.env
  script: nix build .#installMedia.$ISO.config.system.build.isoImage -L --show-trace
  after_script:
    - mkdir -p archive
    - cp -r ./result/* archive
  artifacts:
    paths:
      - 'archive/*'
    reports:
      dotenv: build_iso.env
