# Automatically build Nix Flake Configuration
#
# For more information, see:
# https://github.com/cachix/install-nix-action
name: "Build Nix Flake Configuration"
on:
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.ACCESS_TOKEN }}
    - uses: cachix/cachix-action@v10
      with:
        name: maydayv7-dotfiles
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # Build User Configuration
    - run: nix build .#homeManagerConfigurations.v7.activationPackage
    - run: nix build .#homeManagerConfigurations.navya.activationPackage
    # Build System Configuration
    - run: nix build .#nixosConfigurations.Vortex.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.Futura.config.system.build.toplevel
