name: "ci: Build `nixosConfigurations`"
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - "*"
    paths:
      - "**.lock"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "**.yml"
      - "docs/**"
      - "files/**"
      - "shells/**"
env:
  NIX_SHOW_STATS: 1
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        device: [valkyrie, vortex, futura]
    steps:
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@V28
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: maydayv7-dotfiles
          authToken: "${{ secrets.CACHIX_TOKEN }}"
      - name: Build Configuration
        run: |
          export LC_ALL=C.UTF-8
          ulimit -n 2048
          nix build .#nixosConfigurations.${{ matrix.device }}.config.system.build.toplevel -L --show-trace
