name: "Build Configuration"
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - '.archive/**'
      - '.github/**'
env:
  NIX_SHOW_STATS: 1
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [Vortex, Futura]
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.ACCESS_TOKEN }}
    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: maydayv7-dotfiles
        authToken: '${{ secrets.CACHIX_TOKEN }}'
    - name: Build Configuration
      run: nix build github:maydayv7/dotfiles#nixosConfigurations.${{ matrix.device }}.config.system.build.toplevel
