# Automatically build Nix Flake Configuration on PR
#
# For more information, see:
# https://github.com/cachix/install-nix-action
name: "Build Configuration"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
env:
  NIX_SHOW_STATS: 1
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v14
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.ACCESS_TOKEN }}
    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: maydayv7-dotfiles
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build User V7
      run: nix build github:maydayv7/dotfiles#homeManagerConfigurations.v7.activationPackage
    - name: Build User Navya
      run: nix build github:maydayv7/dotfiles#homeManagerConfigurations.navya.activationPackage
    - name: Build Device Vortex
      run: nix build github:maydayv7/dotfiles#nixosConfigurations.Vortex.config.system.build.toplevel
    - name: Build Device Futura
      run: nix build github:maydayv7/dotfiles#nixosConfigurations.Futura.config.system.build.toplevel
