# Check Nix Flake Configuration Syntax on Push
#
# For more information, see:
# https://github.com/cachix/install-nix-action
name: "Check Syntax"
on:
  push:
    paths-ignore:
      - '**.md'
env:
  NIX_SHOW_STATS: 1
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v14.1
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.ACCESS_TOKEN }}
    - name: Check Syntax
      run: nix flake check github:maydayv7/dotfiles
