# Check Nix Flake Configuration Syntax on Push
#
# For more information, see:
# https://github.com/cachix/install-nix-action
name: "Check Syntax"
on:
  push:
    paths-ignore:
      - '**.md'
env:
  NIX_SHOW_STATS: 1
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v14
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.ACCESS_TOKEN }}
    - name: Import Keys
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add
    - name: Check Syntax
      run: nix flake check github:maydayv7/dotfiles
