name: "ci: Check Syntax"
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - "**.yml"
      - "docs/**"
      - "files/**"
      - "shells/**"
env:
  NIX_SHOW_STATS: 1
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Install Nix
        uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Check Syntax
        run: nix flake check github:maydayv7/dotfiles --keep-going
