name: "Check Syntax"
on:
  push:
    paths-ignore:
      - '**.md'
      - 'files/**'
      - '.github/**'
env:
  NIX_SHOW_STATS: 1
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.ACCESS_TOKEN }}
    - name: Check Syntax
      run: nix flake check github:maydayv7/dotfiles
    - name: Check Shells
      run: nix develop github:maydayv7/dotfiles
