name: "ci: Build default `installMedia`"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    tags:
      - "*"
env:
  NIX_SHOW_STATS: 1
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build Default Install Media
        run: nix build .#installMedia.default.config.system.build.isoImage -L --show-trace
      - name: Upload ISO Image
        uses: actions/upload-artifact@v4
        id: image-upload
        with:
          name: Image
          path: result/iso/nixos.iso
          compression-level: 0
          if-no-files-found: error
