name: "ci: Create Release"
on:
  push:
    tags:
      - "*"
env:
  NIX_SHOW_STATS: 1
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Fix Relative Flake Inputs
        run: nix flake update systems
      - name: Build Default Install Media
        run: nix build .#installMedia.default.config.system.build.isoImage -L --show-trace
      - name: Draft Release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "result/iso/nixos.iso"
          draft: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
