name: "ci: Check `devShells`"
on:
  push:
    paths:
      - "shells/**"
env:
  NIX_SHOW_STATS: 1
jobs:
  shell:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: [cc, format, java, lua, python, rust, sql, video, website]
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: maydayv7-dotfiles
          authToken: "${{ secrets.CACHIX_TOKEN }}"
      - name: Check Shells
        run: nix develop .#${{ matrix.shell }}
