name: "ci: Check `devShells`"
on:
  push:
    paths:
      - "shells/**"
env:
  NIX_SHOW_STATS: 1
jobs:
  shell:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: [cc, format, go, java, lisp, lua, python, rust, video, website]
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cachix
        uses: cachix/cachix-action@v11
        with:
          name: maydayv7-dotfiles
          authToken: "${{ secrets.CACHIX_TOKEN }}"
      - name: Check Shells
        run: nix develop github:maydayv7/dotfiles#${{ matrix.shell }}
