# Warn the Issues and PRs that have had no activity for a specified amount of time
#
# For more information, see:
# https://github.com/actions/stale
name: Mark Stale Issues and PRs

on:
  schedule:
  - cron: '12 0 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        stale-issue-message: 'This Issue is marked stale because it has been open 30 days without any further activity'
        stale-pr-message: 'This PR is marked stale because it has been open 30 days without any further activity'
        days-before-stale: 30
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-all-issue-milestones: true
