name: "chore(flake.lock): Update `inputs`"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
env:
  NIX_SHOW_STATS: 1
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v2.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          accept-flake-config = true
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Update Flake Lock File
      uses: DeterminateSystems/update-flake-lock@main
      with:
        pr-labels: dependencies
        pr-title: >
          chore(flake.lock): Update `inputs`
