name: Update Flake Inputs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
env:
  NIX_SHOW_STATS: 1
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v2.4.0
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        fetch-depth: 0
    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.ACCESS_TOKEN }}
    - name: Update Flake Lock File
      uses: DeterminateSystems/update-flake-lock@v4
