name: "ci: Build and Deploy Site"
on:
  workflow_dispatch:
  push:
    branches: [stable]
    push:
      paths:
        - "site/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build Zola Site
        run: nix build .#website
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: deploy
          folder: result
          single-commit: true
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: maydayv7/maydayv7.github.io
