keys:
  - &key 8C240C0C11293EE56260601CCF616EB19C2765E4
creation_rules:
  - path_regex: secrets/.*$
    key_groups:
    - pgp:
      - *key
  - path_regex: modules/apps/git/secrets/.*$
    key_groups:
    - pgp:
      - *key
  - path_regex: modules/user/passwords/.*$
    key_groups:
    - pgp:
      - *key
