name = "site-git"
main = "index.js"
compatibility_date = "2025-12-15"

[assets]
binding = "ASSETS"
directory = "./public"
run_worker_first = ["/style.css"]

[env.production]
routes = [
  { pattern = "git.maydayv7.cc", custom_domain = true }
]
